services:
  sm-app:
    container_name: sm-app
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      NATS_URL: nats://sm-nats:4222
    depends_on:
      sm-db:
        condition: service_healthy
      sm-nats:
        condition: service_healthy

  sm-nats:
    container_name: sm-nats
    image: nats:2.10-alpine
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - sm-nats-data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 5s
      retries: 10

  sm-db:
    container_name: sm-db
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - sm-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  sm-data:
  sm-nats-data: