services:
  sm-app:
    container_name: sm-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sm-db

  sm-db:
    container_name: sm-db
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - sm-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  sm-data: