/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Упрощенный процесс аутентификации путем передачи идентификатор пользователя и получения токена для дальнейшего прохождения авторизации */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id?: components["schemas"]["UserId"];
                        /** @example Секретная строка */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description Успешная аутентификация */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example e4d2e6b0-cde2-42c5-aac3-0b8316f21e58 */
                            token?: string;
                        };
                    };
                };
                /** @description Невалидные данные */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Регистрация нового пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example Имя */
                        first_name?: string;
                        /** @example Фамилия */
                        second_name?: string;
                        birthdate?: components["schemas"]["BirthDate"];
                        /** @example Хобби, интересы и т.п. */
                        biography?: string;
                        /** @example Москва */
                        city?: string;
                        /** @example Секретная строка */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description Успешная регистрация */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example e4d2e6b0-cde2-42c5-aac3-0b8316f21e58 */
                            user_id?: string;
                        };
                    };
                };
                /** @description Невалидные данные */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получение анкеты пользователя */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Поиск анкет */
        get: {
            parameters: {
                query: {
                    /** @description Условие поиска по имени */
                    first_name: string;
                    /** @description Условие поиска по фамилии */
                    last_name: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успешные поиск пользователя */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                /** @description Невалидные данные */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список пользователей, на которых подписан текущий пользователь. Их посты формируют ленту. */
        get: operations["getFriendList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend/set/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: components["schemas"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пользователь успешно указал своего друга */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friend/delete/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: components["schemas"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пользователь успешно удалил из друзей пользователя */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        text: components["schemas"]["PostText"];
                    };
                };
            };
            responses: {
                /** @description Успешно создан пост */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            post_id: components["schemas"]["PostId"];
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id: components["schemas"]["PostId"];
                        text: components["schemas"]["PostText"];
                    };
                };
            };
            responses: {
                /** @description Успешно изменен пост */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успешно удален пост */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успешно получен пост */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    offset?: components["parameters"]["Offset"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успешно получены посты друзей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostFeed"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post/list/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Посты конкретного пользователя, от новых к старым */
        get: operations["getUserPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialog/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список диалогов текущего пользователя. Возвращает собеседника и идентификатор диалога без превью последнего сообщения. */
        get: operations["getDialogList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialog/{user_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: components["schemas"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        text: components["schemas"]["DialogMessageText"];
                    };
                };
            };
            responses: {
                /** @description Успешно отправлено сообщение */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Идентификатор созданного сообщения */
                            id: string;
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["5xx"];
                503: components["responses"]["5xx"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialog/{user_id}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDialogMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date
         * @description Дата рождения
         * @example 2017-02-01
         */
        BirthDate: string;
        /** @description Идентификатор пользователя */
        UserId: string;
        User: {
            id?: components["schemas"]["UserId"];
            /**
             * @description Имя
             * @example Имя
             */
            first_name?: string;
            /**
             * @description Фамилия
             * @example Фамилия
             */
            second_name?: string;
            birthdate?: components["schemas"]["BirthDate"];
            /**
             * @description Интересы
             * @example Хобби, интересы и т.п.
             */
            biography?: string;
            /**
             * @description Город
             * @example Москва
             */
            city?: string;
        };
        /**
         * @description Идентификатор поста
         * @example 1d535fd6-7521-4cb1-aa6d-031be7123c4d
         */
        PostId: string;
        /**
         * @description Текст поста
         * @example Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lectus mauris ultrices eros in cursus turpis massa.
         */
        PostText: string;
        /**
         * @description Текст сообщения
         * @example Привет, как дела?
         */
        DialogMessageText: string;
        DialogMessage: {
            from: components["schemas"]["UserId"];
            to: components["schemas"]["UserId"];
            /** @description Идентификатор диалога */
            dialog?: string;
            text: components["schemas"]["DialogMessageText"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Пост пользователя */
        Post: {
            id?: components["schemas"]["PostId"];
            text?: components["schemas"]["PostText"];
            created_by?: components["schemas"]["UserId"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Страница ленты постов */
        PostFeed: {
            posts: components["schemas"]["Post"][];
            limit: number;
            offset: number;
        };
        /** @description Страница сообщений диалога */
        DialogMessageList: {
            messages: components["schemas"]["DialogMessage"][];
            limit: number;
            offset: number;
        };
        /** @description Диалог текущего пользователя с другим пользователем */
        DialogSummary: {
            /** @description Идентификатор диалога */
            dialog_id: string;
            user_id: components["schemas"]["UserId"];
        };
    };
    responses: {
        /** @description Невалидные данные ввода */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Неавторизованный доступ */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Ошибка сервера */
        "5xx": {
            headers: {
                /** @description Время, через которое еще раз нужно сделать запрос */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Описание ошибки */
                    message: string;
                    /** @description Идентификатор запроса. Предназначен для более быстрого поиска проблем. */
                    request_id?: string;
                    /** @description Код ошибки. Предназначен для классификации проблем и более быстрого решения проблем. */
                    code?: number;
                };
            };
        };
    };
    parameters: {
        Offset: number;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор пользователя */
                id: components["schemas"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешное получение анкеты пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Невалидные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Анкета не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["5xx"];
            503: components["responses"]["5xx"];
        };
    };
    getFriendList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешно получен список друзей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["401"];
            500: components["responses"]["5xx"];
            503: components["responses"]["5xx"];
        };
    };
    getUserPosts: {
        parameters: {
            query?: {
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                user_id: components["schemas"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешно получены посты пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostFeed"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["5xx"];
            503: components["responses"]["5xx"];
        };
    };
    getDialogList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешно получен список диалогов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogSummary"][];
                };
            };
            401: components["responses"]["401"];
            500: components["responses"]["5xx"];
            503: components["responses"]["5xx"];
        };
    };
    getDialogMessages: {
        parameters: {
            query?: {
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                user_id: components["schemas"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Диалог между двумя пользователями */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogMessageList"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["5xx"];
            503: components["responses"]["5xx"];
        };
    };
}
