// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// BirthDate Дата рождения
type BirthDate = openapi_types.Date

// DialogMessage defines model for DialogMessage.
type DialogMessage struct {
	// From Идентификатор пользователя
	From UserId `json:"from"`

	// Text Текст сообщения
	Text DialogMessageText `json:"text"`

	// To Идентификатор пользователя
	To UserId `json:"to"`
}

// DialogMessageText Текст сообщения
type DialogMessageText = string

// Post Пост пользователя
type Post struct {
	// AuthorUserId Идентификатор пользователя
	AuthorUserId *UserId `json:"author_user_id,omitempty"`

	// Id Идентификатор поста
	Id *PostId `json:"id,omitempty"`

	// Text Текст поста
	Text *PostText `json:"text,omitempty"`
}

// PostId Идентификатор поста
type PostId = string

// PostText Текст поста
type PostText = string

// User defines model for User.
type User struct {
	// Biography Интересы
	Biography *string `json:"biography,omitempty"`

	// Birthdate Дата рождения
	Birthdate *BirthDate `json:"birthdate,omitempty"`

	// City Город
	City *string `json:"city,omitempty"`

	// FirstName Имя
	FirstName *string `json:"first_name,omitempty"`

	// Id Идентификатор пользователя
	Id *UserId `json:"id,omitempty"`

	// SecondName Фамилия
	SecondName *string `json:"second_name,omitempty"`
}

// UserId Идентификатор пользователя
type UserId = string

// N5xx defines model for 5xx.
type N5xx struct {
	// Code Код ошибки. Предназначен для классификации проблем и более быстрого решения проблем.
	Code *int `json:"code,omitempty"`

	// Message Описание ошибки
	Message string `json:"message"`

	// RequestId Идентификатор запроса. Предназначен для более быстрого поиска проблем.
	RequestId *string `json:"request_id,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PostDialogUserIdSendJSONBody defines parameters for PostDialogUserIdSend.
type PostDialogUserIdSendJSONBody struct {
	// Text Текст сообщения
	Text DialogMessageText `json:"text"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	// Id Идентификатор пользователя
	Id       *UserId `json:"id,omitempty"`
	Password *string `json:"password,omitempty"`
}

// PostPostCreateJSONBody defines parameters for PostPostCreate.
type PostPostCreateJSONBody struct {
	// Text Текст поста
	Text PostText `json:"text"`
}

// GetPostFeedParams defines parameters for GetPostFeed.
type GetPostFeedParams struct {
	Offset *float32 `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *float32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutPostUpdateJSONBody defines parameters for PutPostUpdate.
type PutPostUpdateJSONBody struct {
	// Id Идентификатор поста
	Id PostId `json:"id"`

	// Text Текст поста
	Text PostText `json:"text"`
}

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody struct {
	Biography *string `json:"biography,omitempty"`

	// Birthdate Дата рождения
	Birthdate  *BirthDate `json:"birthdate,omitempty"`
	City       *string    `json:"city,omitempty"`
	FirstName  *string    `json:"first_name,omitempty"`
	Password   *string    `json:"password,omitempty"`
	SecondName *string    `json:"second_name,omitempty"`
}

// GetUserSearchParams defines parameters for GetUserSearch.
type GetUserSearchParams struct {
	// FirstName Условие поиска по имени
	FirstName string `form:"first_name" json:"first_name"`

	// LastName Условие поиска по фамилии
	LastName string `form:"last_name" json:"last_name"`
}

// PostDialogUserIdSendJSONRequestBody defines body for PostDialogUserIdSend for application/json ContentType.
type PostDialogUserIdSendJSONRequestBody PostDialogUserIdSendJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostPostCreateJSONRequestBody defines body for PostPostCreate for application/json ContentType.
type PostPostCreateJSONRequestBody PostPostCreateJSONBody

// PutPostUpdateJSONRequestBody defines body for PutPostUpdate for application/json ContentType.
type PutPostUpdateJSONRequestBody PutPostUpdateJSONBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dialog/{user_id}/list)
	GetDialogUserIdList(w http.ResponseWriter, r *http.Request, userId UserId)

	// (POST /dialog/{user_id}/send)
	PostDialogUserIdSend(w http.ResponseWriter, r *http.Request, userId UserId)

	// (PUT /friend/delete/{user_id})
	PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request, userId UserId)

	// (PUT /friend/set/{user_id})
	PutFriendSetUserId(w http.ResponseWriter, r *http.Request, userId UserId)

	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)

	// (POST /post/create)
	PostPostCreate(w http.ResponseWriter, r *http.Request)

	// (PUT /post/delete/{id})
	PutPostDeleteId(w http.ResponseWriter, r *http.Request, id PostId)

	// (GET /post/feed)
	GetPostFeed(w http.ResponseWriter, r *http.Request, params GetPostFeedParams)

	// (GET /post/get/{id})
	GetPostGetId(w http.ResponseWriter, r *http.Request, id PostId)

	// (PUT /post/update)
	PutPostUpdate(w http.ResponseWriter, r *http.Request)

	// (GET /user/get/{id})
	GetUserGetId(w http.ResponseWriter, r *http.Request, id UserId)

	// (POST /user/register)
	PostUserRegister(w http.ResponseWriter, r *http.Request)

	// (GET /user/search)
	GetUserSearch(w http.ResponseWriter, r *http.Request, params GetUserSearchParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /dialog/{user_id}/list)
func (_ Unimplemented) GetDialogUserIdList(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /dialog/{user_id}/send)
func (_ Unimplemented) PostDialogUserIdSend(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /friend/delete/{user_id})
func (_ Unimplemented) PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /friend/set/{user_id})
func (_ Unimplemented) PutFriendSetUserId(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /login)
func (_ Unimplemented) PostLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /post/create)
func (_ Unimplemented) PostPostCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /post/delete/{id})
func (_ Unimplemented) PutPostDeleteId(w http.ResponseWriter, r *http.Request, id PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /post/feed)
func (_ Unimplemented) GetPostFeed(w http.ResponseWriter, r *http.Request, params GetPostFeedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /post/get/{id})
func (_ Unimplemented) GetPostGetId(w http.ResponseWriter, r *http.Request, id PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /post/update)
func (_ Unimplemented) PutPostUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /user/get/{id})
func (_ Unimplemented) GetUserGetId(w http.ResponseWriter, r *http.Request, id UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /user/register)
func (_ Unimplemented) PostUserRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /user/search)
func (_ Unimplemented) GetUserSearch(w http.ResponseWriter, r *http.Request, params GetUserSearchParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDialogUserIdList operation middleware
func (siw *ServerInterfaceWrapper) GetDialogUserIdList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDialogUserIdList(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDialogUserIdSend operation middleware
func (siw *ServerInterfaceWrapper) PostDialogUserIdSend(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDialogUserIdSend(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFriendDeleteUserId operation middleware
func (siw *ServerInterfaceWrapper) PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFriendDeleteUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFriendSetUserId operation middleware
func (siw *ServerInterfaceWrapper) PutFriendSetUserId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFriendSetUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPostCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPostCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPostCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPostDeleteId operation middleware
func (siw *ServerInterfaceWrapper) PutPostDeleteId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PostId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostDeleteId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostFeed operation middleware
func (siw *ServerInterfaceWrapper) GetPostFeed(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostFeedParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostFeed(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostGetId operation middleware
func (siw *ServerInterfaceWrapper) GetPostGetId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PostId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostGetId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPostUpdate operation middleware
func (siw *ServerInterfaceWrapper) PutPostUpdate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserGetId operation middleware
func (siw *ServerInterfaceWrapper) GetUserGetId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserGetId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserSearch operation middleware
func (siw *ServerInterfaceWrapper) GetUserSearch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserSearchParams

	// ------------- Required query parameter "first_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "first_name", r.URL.Query(), &params.FirstName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "first_name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "first_name", Err: err})
		}
		return
	}

	// ------------- Required query parameter "last_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "last_name", r.URL.Query(), &params.LastName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last_name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last_name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dialog/{user_id}/list", wrapper.GetDialogUserIdList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dialog/{user_id}/send", wrapper.PostDialogUserIdSend)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/friend/delete/{user_id}", wrapper.PutFriendDeleteUserId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/friend/set/{user_id}", wrapper.PutFriendSetUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/post/create", wrapper.PostPostCreate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/post/delete/{id}", wrapper.PutPostDeleteId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/post/feed", wrapper.GetPostFeed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/post/get/{id}", wrapper.GetPostGetId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/post/update", wrapper.PutPostUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/get/{id}", wrapper.GetUserGetId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user/register", wrapper.PostUserRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/search", wrapper.GetUserSearch)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FpfbxvHEf8qi2sfSZHUHzvQS+HUSFrARYvYfjIM43S3JDcl7857e60Fg4AkOnEMGU3Q5qFI26R/0dcT",
	"bUZnSqK+wuw3Kmb2SN6RR4m0JLtRHmxJ5N7u/PnNzG9m76nl+O3A97inQmvzqSV5GPheyOmP9WoVf7g8",
	"dKQIlPA9a9OCv0EfehDDESTwGk70PvQZvIYYTkZ/9KAHQ/zI6pSs9WptziYx9PQeDPUOJHAIQ9rU7PEG",
	"NxzqXb2nu3CKu2w8eYK7OL6nuKfwVzsIWsKxccPKpyHu+tQKnSZv2/hbIP2ASyWMIo7v8gIhvkEpGQz1",
	"F5DAAQwgWWHwnd6BPioGMRzi//o59OEEJTrSXzIYwBHEelfvQqKfQQIDiPXnkEDC4FTvwBAO4Aj6cMzw",
	"kwMY0l99Bgd6nxTCJa9gyPAY/QVuDQnum3t4xSpZajvg1qYlPMUbXKIR2jwM7UaRJt/CKSR6lwyY4GkZ",
	"nSZbhUoKr4E7Sf444qF6JNyCzf4Mr1EsvZfRkPzE4BBiIyietYCxztAfTmFIMg8gnq/9SORUZiG5a20+",
	"GFvi4Xihv/Upd5TVwZXTxhnbImZ6F/p6B3r0f2yVrCa3XS4JJZ9wJbfLt+qKywKr/JFUPdZflhgqSX8d",
	"IhyGKYiHqGVfv4A++jbGL090F76HE/T2LhkVobOnX+YMaZUyuJ12eocUMt+TkB8KqZq3bVWEgq/JUTEj",
	"Yb43XkRwWSWLP7HbQQu3Xq3Wbparq+VqzSpZdV+2bWVtWi7uWACU28Ju+Y1fTYCXD6y69Nv486eS161N",
	"6yeVSTappEJX7odc/tLFzRR/os5bnTvwHj6AD/qLHjKFE5KPnk9PnwXMlI73UhmnTPtP6MMA8YueHCJU",
	"0dEF5qWQSAhgeyWERwwDNvL9z4pM/Bs/LDrxO5MATZwc6ZejFKn3cC86Ne8LO1JNXz6KQi7TuF7MK+ev",
	"RQkX9yCuNo7rFBg73WuprHNqTEHxOrF0zd1Y26i7N8o3N1Zr5XVnq1a27RtuubpW2+I3a6trzro7z97n",
	"ennOmXd8ydtMBGHUZq7f8iULhWJ2m6sSc7BuOoqrSDLbFYEIHeE1GG8JVWIhd5nrMy6isO27TPF24Esm",
	"PEe4wo08xSLFWvaWLznjymzNWdtueDazW+JxZK+wO9xRUcjadiRFyKKWksLhIePSD5nwmBPJMAqZimQg",
	"cFUY2itF6qPjZwN5S/gNaQfN7ULPoFco4+ldvZ+H+38obR9AUmKQ5BdiBdR7K3BaKMcWJjI3TWRn4WmS",
	"8TolyxGqSMQ/pRn4dV64v1KhGmDYFIlQFzJUjzy7zQu1Pp4O7dFHMxstE24hd3zPnXfqvyGGY0iQXE2f",
	"Pv3VbIWcCbb01GWDbU66mT0w5E4khdq+i1qmQOK25PJWpJoFx36VY3zEm4j6YIHcgyEMSKhuKVNWDRs8",
	"0PtwNJKtOyIZPQbHmGeJbPZZpeU3hDcqpyiqEWYielOpwFAE4dWppiihyLq/vnf/LvuFaDRbvu2yW9Jp",
	"CoVGLFm/4zI04tdWVleqaFY/4J4dCGvTWluprlQxE9uqSepXXComladpGu5UWsKk9wanHxh0RFrRL9bH",
	"XJnqYzx1B9fibhJTCtGSB08tgYfjCVbJMrCxRkk+W+2UjHiWSixULh+W8pR/1VD+hXm2ULwdLlXTrQlQ",
	"bSnt7ULK9jUk1GEM4RX5GNmM7mId7ekuRuFcnGKImLajOk+sscIVXDRpUc5bW6NGZJF9sVuhtWsLrs3E",
	"Erk8G0UPHnYe4oJZaIXco+AOUgaRxxbWuSy47uLqdw8uajQ+9N3tC/Rvb0kcp8jgHALYMetmg2AKk//S",
	"u3BKPRsSespPp0T0e9S1pCw/xw2hf02hWJeCe27F5S2u+ASR5LmoCIuR+ogeuU1PpAj5f8h0s6y7IKu8",
	"ZLqb877u0sTjCMsx8p5DBq/1ju7CIfSxXs0rotcaDSFXy0DhLlfXAQcDGn3EcITR34Mh9M14w+Dh1WgI",
	"du2cbshWpvpMp8t0vmFSYTrVMx99Tv3BLoNYd8myeSI6nqaZL48ZGdwMmmL9HL9LluavNI7L8UfinhPa",
	"CfF4akWhrV/CCQYzzejMwIqE/yw/W2FTY8xUfKtUUI3vpPz0coriMk1HYIfh731JT2Rain9Qv7tDHPoE",
	"YrTHaEQ3KGqZOosXz7et9P5vuZeXkq+7q/zGVrXsuHy1vL7qbJRt21krV7c+WKvdqK/W+MYHi4laOquk",
	"x+TLeYDM5e4lB+LmyfUlsgwij9FQ9Y1B2hXGOgUzxnDFkTxtx+cTSvz3c7PuXZK73EzpIpxuYRkXmYed",
	"g6iUDx4aLIxHSte0HhCERoTwHAJArQktXbD6X6Dwj5318C1Y/pjn9X8kDqxz7p41rUBrfoRrir32OOJy",
	"e+I2v14PucpdcLi8bkctZW1WC+5pnulndEGzx5AdZK9WqACb+6WEftItSk/vG06gu9lZWa1aLVlt4Yl2",
	"1KaD0uzgRe0tulQpFYvbEm0xR9rarLh/gQSOIaEx/xBeUSuIlOA5jf9j/Qf9AhIkPQPM8mXkhowI4iH0",
	"cPGEGenPsO529QvEHE2d+/Amr1BGn9qsPu9kikP3FIsMb6Ya5Rzp0vvjMMJfM03TdY6qBnZGaU48K7I+",
	"5ur9J8RLK5FLg+OHnGEnzo6C0a3GWeXvfuBeJom60ku8LOEi4F3uJA3bpmPKhT+CKhuFXBblg8LOYNyp",
	"YjuA1WWAxTHNoXNuaWYSC3aBcxLLZdwKXW5yurSLifMOOT85oc1P39INV9ArfjU6F+LZ/tBMma4ytRFu",
	"JW+IMH09Zs7Y5+80LUnSOcL4iu+EDJR582cR8FKeDLn8ZHTsZWXL3G33+7/Mftsb60Wupi9p8jNzb32R",
	"i+nLHhplXnl5L2Mjmk3OgP5iSeDKYznktnSaZ1cgej0vk/LmlZe7Zq/z6gva7YhiPhkl18kLgIYJGB6Q",
	"jOrKVIOWgf9ZBWbq2P/S+5rUMI4PGM96M0LkX7f4BoZwQkSkACRLq6afTYJkrnot+0La5c84X8Nv9W7R",
	"26Hvpps0NXi5btIEyukEmFdSfq8s8jqd/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
