// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// BirthDate Дата рождения
type BirthDate = openapi_types.Date

// DialogMessage defines model for DialogMessage.
type DialogMessage struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Dialog Идентификатор диалога
	Dialog *string `json:"dialog,omitempty"`

	// From Идентификатор пользователя
	From UserId `json:"from"`

	// Text Текст сообщения
	Text DialogMessageText `json:"text"`

	// To Идентификатор пользователя
	To        UserId     `json:"to"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// DialogMessageList Страница сообщений диалога
type DialogMessageList struct {
	Limit    int             `json:"limit"`
	Messages []DialogMessage `json:"messages"`
	Offset   int             `json:"offset"`
}

// DialogMessageText Текст сообщения
type DialogMessageText = string

// DialogSummary Диалог текущего пользователя с другим пользователем
type DialogSummary struct {
	// DialogId Идентификатор диалога
	DialogId string `json:"dialog_id"`

	// UserId Идентификатор пользователя
	UserId UserId `json:"user_id"`
}

// Post Пост пользователя
type Post struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CreatedBy Идентификатор пользователя
	CreatedBy *UserId `json:"created_by,omitempty"`

	// Id Идентификатор поста
	Id *PostId `json:"id,omitempty"`

	// Text Текст поста
	Text      *PostText  `json:"text,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PostFeed Страница ленты постов
type PostFeed struct {
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
	Posts  []Post `json:"posts"`
}

// PostId Идентификатор поста
type PostId = string

// PostText Текст поста
type PostText = string

// User defines model for User.
type User struct {
	// Biography Интересы
	Biography *string `json:"biography,omitempty"`

	// Birthdate Дата рождения
	Birthdate *BirthDate `json:"birthdate,omitempty"`

	// City Город
	City *string `json:"city,omitempty"`

	// FirstName Имя
	FirstName *string `json:"first_name,omitempty"`

	// Id Идентификатор пользователя
	Id *UserId `json:"id,omitempty"`

	// SecondName Фамилия
	SecondName *string `json:"second_name,omitempty"`
}

// UserId Идентификатор пользователя
type UserId = string

// Limit Лимит, ограничивающий кол-во возвращенных сущностей
type Limit = float32

// Offset Оффсет с которого начинать выдачу
type Offset = float32

// N5xx defines model for 5xx.
type N5xx struct {
	// Code Код ошибки. Предназначен для классификации проблем и более быстрого решения проблем.
	Code *int `json:"code,omitempty"`

	// Message Описание ошибки
	Message string `json:"message"`

	// RequestId Идентификатор запроса. Предназначен для более быстрого поиска проблем.
	RequestId *string `json:"request_id,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetDialogMessagesParams defines parameters for GetDialogMessages.
type GetDialogMessagesParams struct {
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDialogUserIdSendJSONBody defines parameters for PostDialogUserIdSend.
type PostDialogUserIdSendJSONBody struct {
	// Text Текст сообщения
	Text DialogMessageText `json:"text"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	// Id Идентификатор пользователя
	Id       *UserId `json:"id,omitempty"`
	Password *string `json:"password,omitempty"`
}

// PostPostCreateJSONBody defines parameters for PostPostCreate.
type PostPostCreateJSONBody struct {
	// Text Текст поста
	Text PostText `json:"text"`
}

// GetPostFeedParams defines parameters for GetPostFeed.
type GetPostFeedParams struct {
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUserPostsParams defines parameters for GetUserPosts.
type GetUserPostsParams struct {
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutPostUpdateJSONBody defines parameters for PutPostUpdate.
type PutPostUpdateJSONBody struct {
	// Id Идентификатор поста
	Id PostId `json:"id"`

	// Text Текст поста
	Text PostText `json:"text"`
}

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody struct {
	Biography *string `json:"biography,omitempty"`

	// Birthdate Дата рождения
	Birthdate  *BirthDate `json:"birthdate,omitempty"`
	City       *string    `json:"city,omitempty"`
	FirstName  *string    `json:"first_name,omitempty"`
	Password   *string    `json:"password,omitempty"`
	SecondName *string    `json:"second_name,omitempty"`
}

// GetUserSearchParams defines parameters for GetUserSearch.
type GetUserSearchParams struct {
	// FirstName Условие поиска по имени
	FirstName string `form:"first_name" json:"first_name"`

	// LastName Условие поиска по фамилии
	LastName string `form:"last_name" json:"last_name"`
}

// PostDialogUserIdSendJSONRequestBody defines body for PostDialogUserIdSend for application/json ContentType.
type PostDialogUserIdSendJSONRequestBody PostDialogUserIdSendJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostPostCreateJSONRequestBody defines body for PostPostCreate for application/json ContentType.
type PostPostCreateJSONRequestBody PostPostCreateJSONBody

// PutPostUpdateJSONRequestBody defines body for PutPostUpdate for application/json ContentType.
type PutPostUpdateJSONRequestBody PutPostUpdateJSONBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody PostUserRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dialog/list)
	GetDialogList(w http.ResponseWriter, r *http.Request)

	// (GET /dialog/{user_id}/list)
	GetDialogMessages(w http.ResponseWriter, r *http.Request, userId UserId, params GetDialogMessagesParams)

	// (POST /dialog/{user_id}/send)
	PostDialogUserIdSend(w http.ResponseWriter, r *http.Request, userId UserId)

	// (PUT /friend/delete/{user_id})
	PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request, userId UserId)

	// (GET /friend/list)
	GetFriendList(w http.ResponseWriter, r *http.Request)

	// (PUT /friend/set/{user_id})
	PutFriendSetUserId(w http.ResponseWriter, r *http.Request, userId UserId)

	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)

	// (POST /post/create)
	PostPostCreate(w http.ResponseWriter, r *http.Request)

	// (PUT /post/delete/{id})
	PutPostDeleteId(w http.ResponseWriter, r *http.Request, id PostId)

	// (GET /post/feed)
	GetPostFeed(w http.ResponseWriter, r *http.Request, params GetPostFeedParams)

	// (GET /post/get/{id})
	GetPostGetId(w http.ResponseWriter, r *http.Request, id PostId)

	// (GET /post/list/{user_id})
	GetUserPosts(w http.ResponseWriter, r *http.Request, userId UserId, params GetUserPostsParams)

	// (PUT /post/update)
	PutPostUpdate(w http.ResponseWriter, r *http.Request)

	// (GET /user/get/{id})
	GetUserById(w http.ResponseWriter, r *http.Request, id UserId)

	// (POST /user/register)
	PostUserRegister(w http.ResponseWriter, r *http.Request)

	// (GET /user/search)
	GetUserSearch(w http.ResponseWriter, r *http.Request, params GetUserSearchParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /dialog/list)
func (_ Unimplemented) GetDialogList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /dialog/{user_id}/list)
func (_ Unimplemented) GetDialogMessages(w http.ResponseWriter, r *http.Request, userId UserId, params GetDialogMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /dialog/{user_id}/send)
func (_ Unimplemented) PostDialogUserIdSend(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /friend/delete/{user_id})
func (_ Unimplemented) PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /friend/list)
func (_ Unimplemented) GetFriendList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /friend/set/{user_id})
func (_ Unimplemented) PutFriendSetUserId(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /login)
func (_ Unimplemented) PostLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /post/create)
func (_ Unimplemented) PostPostCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /post/delete/{id})
func (_ Unimplemented) PutPostDeleteId(w http.ResponseWriter, r *http.Request, id PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /post/feed)
func (_ Unimplemented) GetPostFeed(w http.ResponseWriter, r *http.Request, params GetPostFeedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /post/get/{id})
func (_ Unimplemented) GetPostGetId(w http.ResponseWriter, r *http.Request, id PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /post/list/{user_id})
func (_ Unimplemented) GetUserPosts(w http.ResponseWriter, r *http.Request, userId UserId, params GetUserPostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /post/update)
func (_ Unimplemented) PutPostUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /user/get/{id})
func (_ Unimplemented) GetUserById(w http.ResponseWriter, r *http.Request, id UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /user/register)
func (_ Unimplemented) PostUserRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /user/search)
func (_ Unimplemented) GetUserSearch(w http.ResponseWriter, r *http.Request, params GetUserSearchParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDialogList operation middleware
func (siw *ServerInterfaceWrapper) GetDialogList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDialogList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDialogMessages operation middleware
func (siw *ServerInterfaceWrapper) GetDialogMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDialogMessagesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDialogMessages(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDialogUserIdSend operation middleware
func (siw *ServerInterfaceWrapper) PostDialogUserIdSend(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDialogUserIdSend(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFriendDeleteUserId operation middleware
func (siw *ServerInterfaceWrapper) PutFriendDeleteUserId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFriendDeleteUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFriendList operation middleware
func (siw *ServerInterfaceWrapper) GetFriendList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFriendList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFriendSetUserId operation middleware
func (siw *ServerInterfaceWrapper) PutFriendSetUserId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFriendSetUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPostCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPostCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPostCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPostDeleteId operation middleware
func (siw *ServerInterfaceWrapper) PutPostDeleteId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PostId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostDeleteId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostFeed operation middleware
func (siw *ServerInterfaceWrapper) GetPostFeed(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostFeedParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostFeed(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPostGetId operation middleware
func (siw *ServerInterfaceWrapper) GetPostGetId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PostId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPostGetId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPosts operation middleware
func (siw *ServerInterfaceWrapper) GetUserPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserPostsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPosts(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPostUpdate operation middleware
func (siw *ServerInterfaceWrapper) PutPostUpdate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPostUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserSearch operation middleware
func (siw *ServerInterfaceWrapper) GetUserSearch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserSearchParams

	// ------------- Required query parameter "first_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "first_name", r.URL.Query(), &params.FirstName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "first_name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "first_name", Err: err})
		}
		return
	}

	// ------------- Required query parameter "last_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "last_name", r.URL.Query(), &params.LastName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last_name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last_name", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dialog/list", wrapper.GetDialogList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dialog/{user_id}/list", wrapper.GetDialogMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dialog/{user_id}/send", wrapper.PostDialogUserIdSend)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/friend/delete/{user_id}", wrapper.PutFriendDeleteUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/friend/list", wrapper.GetFriendList)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/friend/set/{user_id}", wrapper.PutFriendSetUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/post/create", wrapper.PostPostCreate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/post/delete/{id}", wrapper.PutPostDeleteId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/post/feed", wrapper.GetPostFeed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/post/get/{id}", wrapper.GetPostGetId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/post/list/{user_id}", wrapper.GetUserPosts)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/post/update", wrapper.PutPostUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/get/{id}", wrapper.GetUserById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user/register", wrapper.PostUserRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/search", wrapper.GetUserSearch)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftfb9vWFf8qF9weKVvyn7Twy9CuaDcgRYu6fQqCgBavZHaSqJKXm41AgG0lWQMbadHtoei2ZF027JVW",
	"rZiWbfkrnPuNhnMuKZEiKVH+kyDOHpra1uW95+/v/M651EOtajfbdou3hKutPdTahmM0ueAO/XbXaloC",
	"f7Ba2pr2jcedbU3XWkaTa2tagz7UNbe6yZsGrjJ5zfAaQlurlHXN5G7VsdrCsvFZ+BsEcAaB3NMZDOEX",
	"uQM+nEMg/wwB9MCXz+RTCOCEwQCGcFqCHgwZ/gPH0MPF8in04RzO5b58zOSu7MqncA5DuSv3oA8nmq7x",
	"LaPZbnB1etNqWU2vqa1VdE1st1Heltfc4I7W6ejaZ7Way3MVs9WnmZqlFXsuH8lHchf6co/JXZJf7sFQ",
	"7qCaqMQ5+KQl/n9PHjDoyX04wj/KblLsuNzltNwdXXO427ZbLifvrJTLSraEPP+APhoUTiGAI7QX9Bke",
	"p4yHv/TIrkfgax1dWylXcjbxoRcqEsAxDGlTtccJbkiml124wF1Wt7Zwl6rdErxFhjXa7YZVNXDDxa9d",
	"3PVhzJ5tx25zR1hKkapt8gwhfkIpGQzltxDAIQwgWGDwQu5AHxUDH45D2/bhHCU6ld+h+U/Bl7tyFwL5",
	"CAIYgC+fQAABgwvyySGcQh/OGP7lEGMN+miUQ7lPCkVuw2PktxRzAe6beHhBG3nHagleR/foWpO7rlHP",
	"0uQ5XEAgd1XI42kxncZbucKxWnWN3PyNx13xwDIzNvsRjlAsuRfTkPzE4Bh8JSieVcBYU/SHCxiSzAPw",
	"87WPRA5lthxuamv3Rpa4P1pob3zNq0IFcSqBIlv4jPJoB3r0r6/p2iY3zBCMvuDC2S59UBPcybDKD6Tq",
	"mfxOZ6gk/XaczMY+gz7CCCPwOWZwLrvwClEEz0WjnkYpGjNkAgcmnd4hhdTnJOSHliM2PzJEVhT8lRzl",
	"MxLmlfIiBlccBLSlcuW9UnmpVK5oulaznaYhtDXNxB0zAuUjy2jY9U/HgTeRWA43BDcfGJSSid1Kwmpm",
	"bmnSlvPF3REEhDgYOn7WpjXHbuKWv3Z4TVvTfrU4rjqLofUWv3K583sTVwu+JWatTmj+JT6AD9rFD/Ha",
	"5py2mQhy0onODCVOR/uEg+5arsgw7M+UdqocPlFJMMRsC0teoPA2aeGknxtRnc4FJVpmCd505zIsGVXt",
	"aTiOsY2/26PimcqGTBRwNX3EFcJnZ1rqyzACJiz1L+jDAGEqZaOJLCLkCwhHkHAMwIcBi1L8N/mZtO41",
	"m4aznZm8IwcwohwDoiD9MVieyoOoTtICRFgkBEdyR3bhF+Q/OQsRuFI+VXk4dwmYmYqey51w1yKJMuHT",
	"sVTjnbK8+bmdGeovFG3INVjKCpdBsOiZje3iaDDbIKhRcXjC1REqXQppMi36MedmAQChiDqXe3KfDE0c",
	"eQi9eWAjP8l1rW27ojieUCSkYGQirNSWhXAi9MNcSREZwU+ARMVcXV6tmXdK760uVUor1Y1KyTDumKXy",
	"cmWDv1dZWq6umFnxNfLtNIDKOfOu7fAms9qu12Sm3bAd5lqCYculsyoy+6rgwnOYYVpty61arTrjDUvo",
	"zOUmM23GLc9t2iYTvNm2HWa1qpZpmV5LME+whrFhO5xxobbmrGnUWwYzGtY3nrHA7vKq8FzWNDzHcpnX",
	"EI5V5S7jju0yq8WqnuN6LhOe07ZwlesaC1nqY9KkqcaGZdcdo725nekZ9ApxMrkr95NI/R8ilocQ6Ayb",
	"pPhC5OhybwEuMuXYQKplhlRrWgSOORmCgyWyRPxLyBGPksL9naj0ACEqk9ZYjiseqLYxQ+uzyaoU/Sm1",
	"UXE81jWXV+2WmXfqv8HHPhvbv8nTJz8qADrhqfMmWw60pw90edVzLLG9jlqGgcQNhzsfeGIz49jvEz0p",
	"dXbUnCGFR4wbkFBdPUb8Vb96KPfhNJKtG7VBPQZnSBGoHe6zxYZdt1oR4UdRlTBj0TeFaKsmxmrViGwK",
	"S5B1P/vyq3X2O6u+2bANk33gVDctgUbUtT9yx1XiVxaWFsqErm3eMtqWtqYtL5QXygjMhtgk9RdVhV1s",
	"hFyxzjMpY9hQDhWtGZf8IfSK05MFBj8kJix+OMWglOxjM0bNY6CawIDRSKEI8cDWkvqvC2rEevJAPgsh",
	"kYoT7qpkSxM5THZEFpodYPBpn3Ch6BkR6IkpyJKaghQePcxBgiM2mK5e6S72pdyFCxoZnI8tHgUafZbn",
	"r9gUJkukkbKLuKija6tK4elrV7e21Nrlgmtjyait3Uum4b37nfu4IIrNhyHz60xGaY7bPh03AvH54r1w",
	"/IaxP56+RawyThCE4/F4G16MuGavG0uwGI4BC6xUg9DO/SvGXuG+iwI9K8zibQhiF7yCI9nFmOrJLlaX",
	"3GRH6FehVi4SauW3OSxd3qKi1Q67kGRcIn9T1laxso6rX2to3h+N+D60ze0rTE4vOSmZYN8504v0xHlJ",
	"xcMlhZ2zlSW4PI5G19FYNqvvnz6nyexQZyM40ocLaqt6qp/KOB36tzSjao7FW+aiyRtc8HFikU+9rJTy",
	"xMf0yEf0RBjorz+n0ticHkBkgOMBk92E92WX4u4U2TKynuNojHMMfaSTeRz3VkfDHJQ0b8x1otN9WIKe",
	"y8dq/dH4kiROYYN8ex8sMPgxfJwuL/aZfETdwRkE6C75DDvxaBrSzWSWKm5fG7Ok7vm6CeU4NN++qHK5",
	"mAdg1rm4DegyoBs5H07RlT0YRp1aNCz2bymUqA47Rs0moz68dhvd9lP205+e0FBol4Evu2TZJGkYXfKq",
	"D2nW3g/vP+kCfmr3mjfApy3jqUcDh/GsAbEsvEylgiEPqLM9oatj1XuT8I+TV35s4nY9FD+FT0hV74ZD",
	"iethjPNMmtqG6/7JduiJ2BzpZ8LmHRqcnINP1xzhzfEga07WKcQsy1ehwfYfeCspJV8xl/idjXKpavKl",
	"0spSdbVkGNXlUnnj/eXKndpSha++X0zUqcjsky/zAjLBCOZ8T0M9uTIHymDkUXmFExVpN5jrlMyYw4vq",
	"tmV6t4X//Vate52dz/gS5vINz1XCEg3yoPjNUsadyIPLNS/x1mnEjm5pRaEgjBqVGRSCOn9aWpA/XIE6",
	"jLxajDq8zO4/+u+IA2vhzWbeIHF0+5ny2ts04xtpMS/hj93k4o8pwn87g6KOrUGY0tMC4xMu3nw+X1uA",
	"zN8NvsUAMXZ2w3InGsHsOcOLcRoMYAjnMSo6nHrbpdNMj9G6nho7DJi6oqdbwrOs6QCS4c/DlxP+f3dx",
	"07j2bo3VKOzVy0GzSMtXbfM6yfPNve2Unr3rc7Pt6fGD7fIZ9dHvADdCQMkqg5kd4WhCgW0g9pEDxMVp",
	"eZUDeB9uZ5XT63gD5HpL8qzp3LVgmxrYzsI1NPnFJb1wAyOC76NzwU+PBdRw8SYLOoWtw+uWG76snzPt",
	"+ycNyYJwfDR6nYcq9IxqnjkqQ199ER17XWCZeLPtzb+4dtm304q8hnZNA7/UO2pXeQntuocysfef38i0",
	"kEbSqaC/GgjceC673HCqm9MLEH1ZKAZ5edVlXe01q768pFfFMOeDCFzHX0dSREDRgCCqKxNf44uF/7QC",
	"M3Hsf+nbY/QloNEBoxF/TIjkq5U/YSdCPCQjSOZWTT4aJ0mueg3jStolz5it4XO5m/VdtSuX3hu7NFWJ",
	"cjEOzBspvzeWeZ3O/wIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
